services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  HeimrichHannot\FileManagerBundle\:
    resource: '../../{Controller,DataContainer,EventListener,Util}/*'

  HeimrichHannot\FileManagerBundle\Controller\FrontendModule\FileManagerModuleController:
    calls:
      - [setEncoreFrontendAsset, ['@?HeimrichHannot\EncoreBundle\Asset\FrontendAsset']]
