services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
    #bind:
    #  $bundleConfig: '%huh_file_manager%'

  HeimrichHannot\FileManagerBundle\:
    resource: '../../{Controller,DataContainer,EventListener}/*'
